# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random(size=(2,3,5))
a

array([[[0.2665695 , 0.26282285, 0.5990681 , 0.4582262 , 0.70595617],
        [0.40019013, 0.01643891, 0.80620327, 0.18341099, 0.12539719],
        [0.77799206, 0.23009637, 0.16444732, 0.66948952, 0.06094368]],

       [[0.84915366, 0.45877998, 0.42620202, 0.59665967, 0.53259852],
        [0.42719951, 0.68085875, 0.69480072, 0.73152132, 0.30526256],
        [0.73401618, 0.83183246, 0.14467084, 0.46188494, 0.22890732]]])

In [4]:
# Method 2
a = np.random.randint(50,size = (2,3,5))
a

array([[[24, 40,  7, 42, 21],
        [32, 15,  7, 35, 11],
        [28, 18, 34, 34, 48]],

       [[43,  0, 47, 31, 47],
        [38, 24, 14, 20, 32],
        [17, 18, 35, 28,  8]]])

In [5]:
# Method 3
a = np.random.random_integers(55, 95, size = (2,3,5))
a

C:\Users\Alvaro Camacho\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(55, 95 + 1) instead
  


array([[[91, 66, 55, 77, 72],
        [74, 86, 84, 95, 83],
        [86, 83, 73, 91, 60]],

       [[86, 82, 86, 58, 62],
        [90, 82, 89, 60, 88],
        [56, 78, 93, 87, 69]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a) 

[[[91 66 55 77 72]
  [74 86 84 95 83]
  [86 83 73 91 60]]

 [[86 82 86 58 62]
  [90 82 89 60 88]
  [56 78 93 87 69]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
np.size(a) is np.size(b)

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
a+b # ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [11]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [49]:
# your code/answer here
d = a+c
d

array([[[92., 67., 56., 78., 73.],
        [75., 87., 85., 96., 84.],
        [87., 84., 74., 92., 61.]],

       [[87., 83., 87., 59., 63.],
        [91., 83., 90., 61., 89.],
        [57., 79., 94., 88., 70.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [50]:
# your code/answer here
print(a)
print(d)
print(a+1)

# each element of a was added with each element of d which was 1, so a + d == a + 1

[[[91 66 55 77 72]
  [74 86 84 95 83]
  [86 83 73 91 60]]

 [[86 82 86 58 62]
  [90 82 89 60 88]
  [56 78 93 87 69]]]
[[[92. 67. 56. 78. 73.]
  [75. 87. 85. 96. 84.]
  [87. 84. 74. 92. 61.]]

 [[87. 83. 87. 59. 63.]
  [91. 83. 90. 61. 89.]
  [57. 79. 94. 88. 70.]]]
[[[92 67 56 78 73]
  [75 87 85 96 84]
  [87 84 74 92 61]]

 [[87 83 87 59 63]
  [91 83 90 61 89]
  [57 79 94 88 70]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [51]:
# your code here
e = a*c
e

array([[[91., 66., 55., 77., 72.],
        [74., 86., 84., 95., 83.],
        [86., 83., 73., 91., 60.]],

       [[86., 82., 86., 58., 62.],
        [90., 82., 89., 60., 88.],
        [56., 78., 93., 87., 69.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e is a # it is not the same because despite the fact that the result of each element multiplied by 1, 
#equals the same  value its different.

False

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [52]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_min, d_max, d_mean)

56.0 96.0 79.06666666666666


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [53]:
# your code here
f = np.empty((2,3,5), dtype=object)
f
g = np.empty((2,3,5), dtype=object)


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [54]:
# your code here
f = np.array([np.where(z > d_min and z < d_mean, 25, z) for x in d for y in x for z in y])
f = f.reshape(2,3,5)
f =np.array([np.where(z > d_mean and z < d_max, 75, z) for x in f for y in x for z in y])
f = f.reshape(2,3,5)
f =np.array([np.where(z == d_mean, 50, z) for x in f for y in x for z in y])
f = f.reshape(2,3,5)
f =np.array([np.where(z == d_min, 0, z) for x in f for y in x for z in y])
f = f.reshape(2,3,5)
f =np.array([np.where(z == d_max, 100, z) for x in f for y in x for z in y])
f = f.reshape(2,3,5)
print(d)
print(f)

            


[[[92. 67. 56. 78. 73.]
  [75. 87. 85. 96. 84.]
  [87. 84. 74. 92. 61.]]

 [[87. 83. 87. 59. 63.]
  [91. 83. 90. 61. 89.]
  [57. 79. 94. 88. 70.]]]
[[[ 75.  25.   0.  25.  25.]
  [ 25.  75.  75. 100.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [55]:
# your code here
print(d)
print(f)

[[[92. 67. 56. 78. 73.]
  [75. 87. 85. 96. 84.]
  [87. 84. 74. 92. 61.]]

 [[87. 83. 87. 59. 63.]
  [91. 83. 90. 61. 89.]
  [57. 79. 94. 88. 70.]]]
[[[ 75.  25.   0.  25.  25.]
  [ 25.  75.  75. 100.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  75.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [59]:
g = np.empty(f.shape, dtype=object)
for x in range(f.shape[0]):
    for y in range(f.shape[1]):
        for z in range(f.shape[2]):
            if f[x, y, z] == 0:
                g[x, y, z] = 'A'
            elif f[x, y, z] == 25:
                g[x, y, z] = 'B'
            elif f[x, y, z] == 50:
                g[x, y, z] = 'C'
            elif f[x, y, z] == 75:
                g[x, y, z] = 'D'
            elif f[x, y, z] == 100:
                g[x, y, z] = 'E'
                
print(g)

        

         
    


[[['D' 'B' 'A' 'B' 'B']
  ['B' 'D' 'D' 'E' 'D']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'D' 'B' 'B']
  ['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']]]
